#!/bin/bash

paths=("$@")
table+="test status\n"
table+="---- ------\n"

for path in "${paths[@]}"; do
    if ! [[ -e "$path" ]]; then
        printf "run_tests: binary not found at '%s'\n" "$path" >&2
        exit 1
    fi

    table+="$path $($path && printf "passed" || printf "failed")\n"
done

printf "%b\n" "$table" | column -t
